FORMATIONS_INFO_DB = "Data/Formations_info.csv"

PITCH_LENGTH = 105
PITCH_WIDTH = 68
PITCH_COLOUR = '#2e8b57'

AREA_CAPTURE_MIN_THRESHOLD = 550 # in m^2

MY_TEAM_NAME = "Home"
OPPONENT_TEAM_NAME = "Away"

HOME_PLAYER_COLOUR = '#3498db'
HOME_GK_COLOUR = "#0ff1b5"

AWAY_PLAYER_COLOUR = '#e74c3c'
AWAY_GK_COLOUR = '#e67e22'

MODE_ATTACKING = "Attacking"
MODE_DEFENSIVE = "Defensive"
MODE_BALANCED = "Balanced"
MODE_UNKNOWN = "Unknown"